// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR_oLPGKegzJ22bP--y708vs37ELGC-1Q',
    appId: '1:636564319853:web:0fe0886834b2dbcbbad964',
    messagingSenderId: '636564319853',
    projectId: 'flowora-dd51c',
    authDomain: 'flowora-dd51c.firebaseapp.com',
    storageBucket: 'flowora-dd51c.firebasestorage.app',
    measurementId: 'G-MSG3HV3DFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEEWAPbFF3quo3mdghQJSUNAVINyBlCo4',
    appId: '1:636564319853:android:792290502cf99dbcbad964',
    messagingSenderId: '636564319853',
    projectId: 'flowora-dd51c',
    storageBucket: 'flowora-dd51c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-oPA5cLqKu5upzfdvueOS5n-rSN3IeOA',
    appId: '1:636564319853:ios:fa2f6b9f231ccfeabad964',
    messagingSenderId: '636564319853',
    projectId: 'flowora-dd51c',
    storageBucket: 'flowora-dd51c.firebasestorage.app',
    iosBundleId: 'com.example.flowerss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-oPA5cLqKu5upzfdvueOS5n-rSN3IeOA',
    appId: '1:636564319853:ios:fa2f6b9f231ccfeabad964',
    messagingSenderId: '636564319853',
    projectId: 'flowora-dd51c',
    storageBucket: 'flowora-dd51c.firebasestorage.app',
    iosBundleId: 'com.example.flowerss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR_oLPGKegzJ22bP--y708vs37ELGC-1Q',
    appId: '1:636564319853:web:cdc45b36544e33c9bad964',
    messagingSenderId: '636564319853',
    projectId: 'flowora-dd51c',
    authDomain: 'flowora-dd51c.firebaseapp.com',
    storageBucket: 'flowora-dd51c.firebasestorage.app',
    measurementId: 'G-0BEPHGLJBT',
  );
}
